# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5159eb1ef031d80c9e866ee1b3ef8aaff5e17c405f0bef6785fd29323a984b0916186c7885a3cac5fa52912f5a77564515cd630dfaa1015a1d9fac4db8fa1948

test:
  secret_key_base: b4c160c31ba1854fcc0517e6cfb28eb39d35d1b7054703e18eb884236727610d239707ffd9dae290bdbcded5749d5c3c16ce0bff58ec8158ea3c52e1ea23c863

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
